# Generated by Django 4.1 on 2022-12-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
