# Generated by Django 4.1 on 2022-12-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='detail',
            field=models.TextField(max_length=400),
        ),
    ]
