# Generated by Django 4.1 on 2022-12-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_drink_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='detail',
            field=models.TextField(max_length=500),
        ),
    ]
